In [17]:
import pandas as pd

df = pd.read_csv("../data/games.csv")

df.head()

C:\Users\natha\AppData\Local\Temp\ipykernel_15988\940427846.py:3: DtypeWarning: Columns (0: gameSubLabel) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/games.csv")

,gameId,gameDateTimeEst,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,winner,gameType,attendance,arenaId,gameLabel,gameSubLabel,seriesGameNumber
0,22500642,2026-01-23 17:00:00,Portland,Trail Blazers,1610612757,Toronto,Raptors,1610612761,98,110,1610612761,NaN,17438.0,NaN,NaN,NaN,NaN
1,22500640,2026-01-23 16:30:00,Milwaukee,Bucks,1610612749,Denver,Nuggets,1610612743,100,102,1610612743,NaN,17341.0,NaN,AWS NBA Rivals Week,NaN,NaN
2,22500641,2026-01-23 15:00:00,Oklahoma City,Thunder,1610612760,Indiana,Pacers,1610612754,114,117,1610612754,NaN,18203.0,NaN,NaN,NaN,NaN
3,22500639,2026-01-23 15:00:00,Memphis,Grizzlies,1610612763,New Orleans,Pelicans,1610612740,127,133,1610612740,NaN,14174.0,NaN,NaN,NaN,NaN
4,22500636,2026-01-23 14:30:00,Atlanta,Hawks,1610612737,Phoenix,Suns,1610612756,110,103,1610612737,NaN,15461.0,NaN,NaN,NaN,NaN

In [18]:
df.shape

(72623, 17)

In [19]:
df.columns

Index(['gameId', 'gameDateTimeEst', 'hometeamCity', 'hometeamName',
       'hometeamId', 'awayteamCity', 'awayteamName', 'awayteamId', 'homeScore',
       'awayScore', 'winner', 'gameType', 'attendance', 'arenaId', 'gameLabel',
       'gameSubLabel', 'seriesGameNumber'],
      dtype='str')

In [20]:
df.isnull().sum()

gameId                  0
gameDateTimeEst         0
hometeamCity            0
hometeamName            0
hometeamId              0
awayteamCity            0
awayteamName            0
awayteamId              0
homeScore               0
awayScore               0
winner                  0
gameType              670
attendance           5036
arenaId               744
gameLabel           68682
gameSubLabel        72392
seriesGameNumber    66885
dtype: int64

In [21]:
df[['hometeamCity', 'awayteamCity', 'homeScore', 'awayScore']].head()

    hometeamCity awayteamCity  homeScore  awayScore
0       Portland      Toronto         98        110
1      Milwaukee       Denver        100        102
2  Oklahoma City      Indiana        114        117
3        Memphis  New Orleans        127        133
4        Atlanta      Phoenix        110        103

In [22]:
df['winner'].value_counts()

winner
1610612738    4122
1610612747    4047
1610612755    3384
1610612744    3207
1610612752    3183
1610612737    3172
1610612765    3085
1610612758    2844
1610612760    2817
1610612756    2718
1610612741    2711
1610612745    2687
1610612749    2656
1610612759    2646
1610612757    2521
1610612764    2452
1610612762    2410
1610612739    2304
1610612743    2221
1610612754    2194
1610612746    2041
1610612742    2039
1610612751    1815
1610612748    1811
1610612753    1517
1610612750    1333
1610612761    1287
1610612766    1280
1610612763    1171
1610612740     948
Name: count, dtype: int64

In [23]:
df[['hometeamName','awayteamName','winner']].head()

    hometeamName awayteamName      winner
0  Trail Blazers      Raptors  1610612761
1          Bucks      Nuggets  1610612743
2        Thunder       Pacers  1610612754
3      Grizzlies     Pelicans  1610612740
4          Hawks         Suns  1610612737

In [24]:
df['home_win'] = (df['winner'] == df['hometeamId']).astype(int)
df[['hometeamName','awayteamName','home_win']].head()

    hometeamName awayteamName  home_win
0  Trail Blazers      Raptors         0
1          Bucks      Nuggets         0
2        Thunder       Pacers         0
3      Grizzlies     Pelicans         0
4          Hawks         Suns         1

In [25]:
df['score_diff'] = df['homeScore'] - df['awayScore']

df[['hometeamName','awayteamName','homeScore','awayScore','score_diff','home_win']].head()

    hometeamName awayteamName  homeScore  awayScore  score_diff  home_win
0  Trail Blazers      Raptors         98        110         -12         0
1          Bucks      Nuggets        100        102          -2         0
2        Thunder       Pacers        114        117          -3         0
3      Grizzlies     Pelicans        127        133          -6         0
4          Hawks         Suns        110        103           7         1

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Features and target
X = df[['score_diff']]
y = df['home_win']

# Train / test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate
preds = model.predict(X_test)
accuracy = accuracy_score(y_test, preds)

accuracy

1.0